apiVersion: v1
data:
  vector.yaml: |
    data_dir: /vector-data-buffer
    sinks:
      clickhouse:
        batch:
          max_events: 10000
          timeout_secs: 5
        compression: gzip
        database: audit
        endpoint: http://clickhouse.clickhouse.svc.cluster.local:8123
        inputs:
        - prepare_storage
        request:
          retry_attempts: 3
          retry_initial_backoff_secs: 1
          retry_max_duration_secs: 10
        table: events
        type: clickhouse
      console_debug:
        encoding:
          codec: json
        inputs:
        - prepare_storage
        type: console
      opensearch:
        api_version: v7
        batch:
          max_events: 5000
          timeout_secs: 5
        bulk:
          action: index
          index: '{{ .event_date }}'
        endpoints:
        - http://opensearch-cluster-master.opensearch.svc.cluster.local:9200
        inputs:
        - prepare_storage
        mode: bulk
        request:
          retry_attempts: 3
          retry_initial_backoff_secs: 1
          retry_max_duration_secs: 10
        type: elasticsearch
      prometheus_exporter:
        address: 0.0.0.0:9090
        inputs:
        - internal_metrics
        type: prometheus_exporter
      redpanda:
        acknowledgements:
          enabled: true
        batch:
          max_bytes: 1048576
          timeout_secs: 1
        bootstrap_servers: redpanda.redpanda.svc.cluster.local:9093
        compression: lz4
        encoding:
          codec: json
        inputs:
        - enrich
        key_field: tenant_id
        sasl:
          enabled: true
          mechanism: SCRAM-SHA-256
          password: changeme_producer123
          username: turia-producer
        topic: audit.events.v1
        type: kafka
    sources:
      http_ingest:
        address: 0.0.0.0:8080
        encoding: json
        type: http_server
      internal_metrics:
        type: internal_metrics
      kafka_consumer:
        auto_offset_reset: earliest
        bootstrap_servers: redpanda.redpanda.svc.cluster.local:9093
        decoding:
          codec: json
        group_id: audit-consumer-group
        sasl:
          enabled: true
          mechanism: SCRAM-SHA-256
          password: changeme_producer123
          username: turia-producer
        topics:
        - audit.events.v1
        type: kafka
    transforms:
      enrich:
        inputs:
        - validate
        source: |
          .event_id = uuid_v7()
          .received_at = now()
          .event_date = format_timestamp!(.timestamp || now(), "%Y-%m-%d")
          .processing.vector_node = get_hostname!()
          .action.name = downcase(string!(.action.name))
          .tenant_id = .tenant_id || "default_tenant"
        type: remap
      prepare_storage:
        inputs:
        - kafka_consumer
        source: |
          # Events already enriched from production, ensure event_date for partitioning
          .event_date = .event_date || format_timestamp!(now(), "%Y-%m-%d")
        type: remap
      validate:
        inputs:
        - http_ingest
        source: |
          assert!(exists(.actor.id), "actor.id is required")
          assert!(exists(.action.name), "action.name is required")
          assert!(exists(.resource.type), "resource.type is required")
          assert!(exists(.resource.id), "resource.id is required")
        type: remap
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: vector
    meta.helm.sh/release-namespace: vector
  creationTimestamp: "2025-12-09T15:16:06Z"
  labels:
    app.kubernetes.io/component: Aggregator
    app.kubernetes.io/instance: vector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vector
    app.kubernetes.io/version: 0.51.1-distroless-libc
    helm.sh/chart: vector-0.48.0
  name: vector
  namespace: vector
  resourceVersion: "1327996"
  uid: d468677f-c002-40d4-a1e7-9ce28cecfb24
